exclude: [
    "laravelcs.sublime-project",
    "laravelcs.sublime-workspace",
    ".vagrant",
    ".gitignore",
    "README.md",
    "Vagrantfile",
    "package.json",
    "Gruntfile.js",
    "node_modules",
    "bower.json",
    "bower_components",
    "dist",
    "style.scss"
]
url: http://Ilyes512.github.io/LaravelCS

markdown: redcarpet
pygments: true